remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

title: NOAA Omics Data Management Guide
description: [A short description of your site's purpose]

minimal_mistakes_skin: default
search: true

defaults:
  # _docs
  - scope:
      path: ""
      type: main
    values:
      sidebar:
        nav: "main"
